# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts && npm install typescript --no-save

# Copy source and build
COPY . .
RUN npx tsc

CMD ["node", "dist/index.js"]
